name: ci

on:
  push:
    branches:
      - '*'

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          mkdir ci
          cd ci
          cmake ..
          cmake --build . --config Release
          cmake --install .
      - name: which
        run: which jp
      - name: test different json
        run: jp ./example/a.json ./example/b.json
        continue-on-error: true
      - name: test same json
        run: jp ./example/a.json ./example/a1.json
      - name: test same json with case insensitive
        run: jp ./example/a.json ./example/a2.json -cf
      - name: test select
        run: jp ./example/a.json ./example/a2.json -s .world
        continue-on-error: true
      - name: test unfold
        run: jp ./example/a.json ./example/b.json -f
        continue-on-error: true
      - name: test dir
        run: jp ./example
        continue-on-error: true

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          mkdir ci
          cd ci
          cmake ..
          cmake --build . --config Release
          cmake --install .
      - name: which
        run: which jp
      - name: test different json
        run: jp ./example/a.json ./example/b.json
        continue-on-error: true
      - name: test same json
        run: jp ./example/a.json ./example/a1.json
      - name: test same json with case insensitive
        run: jp ./example/a.json ./example/a2.json -cf
      - name: test select
        run: jp ./example/a.json ./example/a2.json -s .world
        continue-on-error: true
      - name: test unfold
        run: jp ./example/a.json ./example/b.json -f
        continue-on-error: true
      - name: test dir
        run: jp ./example
        continue-on-error: true

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          mkdir ci
          cd ci
          cmake ..
          cmake --build . --config Release
          cmake --install .
      - name: which
        run: Get-Command jp.exe
      - name: powershell width
        run: echo (Get-Host).UI.RawUI.WindowSize.Width
      - name: test different json
        run: jp ./example/a.json ./example/b.json
        continue-on-error: true
      - name: test same json
        run: jp ./example/a.json ./example/a1.json
      - name: test same json with case insensitive
        run: jp ./example/a.json ./example/a2.json -cf
      - name: test select
        run: jp ./example/a.json ./example/a2.json -s .world
        continue-on-error: true
      - name: test unfold
        run: jp ./example/a.json ./example/b.json -f
        continue-on-error: true
      - name: test dir
        run: jp ./example
        continue-on-error: true
