name: release

on:
  push:
    tags:
      - '*'

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cmake . && cmake --build . --config Release
    - name: Package
      run: tar czf jp-bin-linux.tar.gz jp
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./jp-bin-linux.tar.gz
        asset_name: jp-bin-linux.tar.gz
        tag: ${{ github.ref }}

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cmake . && cmake --build . --config Release
    - name: Package
      run: zip --junk-paths jp-bin-macos.zip jp
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./jp-bin-macos.zip
        asset_name: jp-bin-macos.zip
        tag: ${{ github.ref }}

  windows:
    name: release for windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cmake . && cmake --build . --config Release
    - name: Package
      run: Compress-Archive jp.exe jp-bin-windows.zip
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./jp-bin-windows.zip
        asset_name: jp-bin-windows.zip
        tag: ${{ github.ref }}
