name: release

on:
  push:
    tags:
      - '*'

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cmake . && cmake --build . --config Release
    - name: Package
      run: tar czf linux-jp.tar.gz jp
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./linux-jp.tar.gz
        asset_name: linux-jp.tar.gz
        tag: ${{ github.ref }}

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cmake . && cmake --build . --config Release
    - name: Package
      run: zip --junk-paths macos-jp.zip jp
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./macos-jp.zip
        asset_name: macos-jp.zip
        tag: ${{ github.ref }}

  windows:
    name: release for windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cmake . && cmake --build . --config Release
    - name: Package
      run: Compress-Archive jp.exe windows-jp.zip
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./windows-jp.zip
        asset_name: windows-jp.zip
        tag: ${{ github.ref }}
